apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: nats-main
    name: nats-main
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: nats
      generation: null
      importPolicy: {}
      name: latest
  status:
    dockerImageRepository: ""
