apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift -f docker-compose.yml convert
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: spark-worker1
    name: spark-worker1
  spec:
    replicas: 1
    selector:
      io.kompose.service: spark-worker1
    strategy:
      resources: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: spark-worker1
      spec:
        containers:
        - args:
          - bin/spark-class
          - org.apache.spark.deploy.worker.Worker
          - spark://spark-master:7077
          env:
          - name: SPARK_CONF_DIR
            value: /conf
          - name: SPARK_PUBLIC_DNS
            value: localhost
          - name: SPARK_WORKER_CORES
            value: "1"
          - name: SPARK_WORKER_MEMORY
            value: 1g
          - name: SPARK_WORKER_PORT
            value: "8881"
          - name: SPARK_WORKER_WEBUI_PORT
            value: "8081"
          image: ' '
          name: spark-worker1
          ports:
          - containerPort: 8081
          resources: {}
        hostname: spark-worker1
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spark-worker1
        from:
          kind: ImageStreamTag
          name: spark-worker1:2.3.1-hadoop-3.0
      type: ImageChange
  status: {}
