apiVersion: v1
kind: Template
metadata:
  name: redis-template
  annotations:
    description: "Description"
    iconClass: "icon-redis"
    tags: "database,nosql"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose --provider openshift -f docker-compose.yml convert
      kompose.version: 1.18.0 ()
    creationTimestamp: null
    labels:
      io.kompose.service: spark-master
    name: spark-master
  spec:
    ports:
    - name: "7001"
      port: 7001
      targetPort: 7001
    - name: "7002"
      port: 7002
      targetPort: 7002
    - name: "7003"
      port: 7003
      targetPort: 7003
    - name: "7004"
      port: 7004
      targetPort: 7004
    - name: "7005"
      port: 7005
      targetPort: 7005
    - name: "6066"
      port: 6066
      targetPort: 6066
    - name: "7077"
      port: 7077
      targetPort: 7077
    - name: "8080"
      port: 8080
      targetPort: 8080
    selector:
      io.kompose.service: spark-master
  status:
    loadBalancer: {}
