apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: netcat
  name: netcat
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: netcat
    spec:
      containers:
      - command:
        - sh
        - -c
        - nc -lk 9988 | nc -lk 9989
        image: subfuzion/netcat
        name: netcat
        ports:
        - containerPort: 9988
        - containerPort: 9989
        resources: {}
      hostname: netcat
      restartPolicy: Always
status: {}
