apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker2
  name: spark-worker2
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8081
  selector:
    io.kompose.service: spark-worker2
status:
  loadBalancer: {}
