apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
      - args:
        - bin/spark-class
        - org.apache.spark.deploy.master.Master
        - -h
        - spark-master
        env:
        - name: MASTER
          value: spark://master:7077
        - name: SPARK_CONF_DIR
          value: /conf
        - name: SPARK_PUBLIC_DNS
          value: localhost
        image: gettyimages/spark:2.3.1-hadoop-3.0
        name: spark-master
        ports:
        - containerPort: 7001
        - containerPort: 7002
        - containerPort: 7003
        - containerPort: 7004
        - containerPort: 7005
        - containerPort: 6066
        - containerPort: 7077
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
