apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: spark-worker1
  name: spark-worker1
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: spark-worker1
    spec:
      containers:
      - args:
        - bin/spark-class
        - org.apache.spark.deploy.worker.Worker
        - spark://spark-master:7077
        env:
        - name: SPARK_CONF_DIR
          value: /conf
        - name: SPARK_PUBLIC_DNS
          value: localhost
        - name: SPARK_WORKER_CORES
          value: "1"
        - name: SPARK_WORKER_MEMORY
          value: 1g
        - name: SPARK_WORKER_PORT
          value: "8881"
        - name: SPARK_WORKER_WEBUI_PORT
          value: "8081"
        image: gettyimages/spark:2.3.1-hadoop-3.0
        name: spark-worker1
        ports:
        - containerPort: 8081
        resources: {}
      hostname: spark-worker1
      restartPolicy: Always
status: {}
