version: '3'

services:
  spark-master:
    image: gettyimages/spark:2.3.1-hadoop-3.0
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7077
      - 6066
    ports:
#      - 4040:4040
      - 7001:7001
      - 7002:7002
      - 7003:7003
      - 7004:7004
      - 7005:7005
      - 6066:6066
      - 7077:7077
      - 8080:8080

  spark-worker1:
    image: gettyimages/spark:2.3.1-hadoop-3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    hostname: spark-worker1
    ports:
      - 8081:8081

  spark-worker2:
    image: gettyimages/spark:2.3.1-hadoop-3.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 8881
    hostname: spark-worker2
    links:
      - spark-master
    ports:
      - 8082:8081

  nats-main:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    container_name: nats-main
    hostname: nats-main

  netcat:
    image: subfuzion/netcat
    hostname: netcat
    entrypoint:
      - sh
      - -c
      - "nc -lk 9988 | nc -lk 9989"
    ports:
      - 9988:9988
      - 9989:9989